// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJi0haOzwExV_-k4oCXkKHNJQRY_M384w',
    appId: '1:393250629301:web:23b8a7d6a54c43ed6a40fc',
    messagingSenderId: '393250629301',
    projectId: 'contest-app-94050',
    authDomain: 'contest-app-94050.firebaseapp.com',
    storageBucket: 'contest-app-94050.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuBbskDjvf_zZ78zpiOVK7v3q00lptmw',
    appId: '1:393250629301:android:44577a5a19334df56a40fc',
    messagingSenderId: '393250629301',
    projectId: 'contest-app-94050',
    storageBucket: 'contest-app-94050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ElgN4QygyKkzL2DsSrUlCMUaUynyclM',
    appId: '1:393250629301:ios:fc96208a8107dab36a40fc',
    messagingSenderId: '393250629301',
    projectId: 'contest-app-94050',
    storageBucket: 'contest-app-94050.firebasestorage.app',
    iosBundleId: 'com.contestlive.contestLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ElgN4QygyKkzL2DsSrUlCMUaUynyclM',
    appId: '1:393250629301:ios:fc96208a8107dab36a40fc',
    messagingSenderId: '393250629301',
    projectId: 'contest-app-94050',
    storageBucket: 'contest-app-94050.firebasestorage.app',
    iosBundleId: 'com.contestlive.contestLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJi0haOzwExV_-k4oCXkKHNJQRY_M384w',
    appId: '1:393250629301:web:6a86c4299a6b8cb76a40fc',
    messagingSenderId: '393250629301',
    projectId: 'contest-app-94050',
    authDomain: 'contest-app-94050.firebaseapp.com',
    storageBucket: 'contest-app-94050.firebasestorage.app',
  );

}